version: "3.8"

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  # Fastify API Service
  api:
    image: "node:alpine"
    working_dir: /app
    depends_on:
      - mongodb

  # Vue.js App Service
  front:
    image: "node:alpine"
    working_dir: /app
    depends_on:
      - api
