version: "3.8"

services:
  database:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"

  api:
    image: node:alpine
    working_dir: /repo
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev:api"
    depends_on:
      - database
    volumes:
      - ./:/repo
      - /repo/node_modules

  front:
    image: node:alpine
    working_dir: /repo
    environment:
      - PORT=5173
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev:front"
    depends_on:
      - api
    volumes:
      - ./:/repo
      - /repo/node_modules