version: '3.4'
services:
  front:
    image: "node:24-alpine"
    working_dir: /app
    volumes:
#      - /app.web/node_modules
      - ./app.web:/app
    ports:
      - "80:80"
    environment:
      HOST: 0.0.0.0
      PORT: 80
    command: sh -c "npm i & npm run dev"
    depends_on:
      - mongo
    env_file:
      - .env

volumes:
  mongodb-data:
    driver: local