# https://stackoverflow.com/questions/69134075/im-having-a-problem-building-docker-for-my-nuxtjs-app-hot-reload-not-working

version: '3.4'
services:
  mongo:
    restart: always
    image: mongo:8.0
    container_name: sagace-database-mongo
    command: mongod --auth --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  front:
    image: "node:24-alpine"
    working_dir: /app
    volumes:
      - /app.web/node_modules
      - ./app.web:/app
    ports:
      - "80:80"
    environment:
      HOST: 0.0.0.0
      PORT: 80
    command: sh -c "npm run dev"
    depends_on:
      - mongo
    env_file:
      - .env

volumes:
  mongodb-data:
    driver: local